<div class="section-footer">
    <footer class="awesome-footer">
        <div class="container grid-xl">
            <div class="columns">
                <div class="footer-container disclaimer-container column col-8 col-sm-12 col-mx-auto"><span
                        class="text-bold">DISCLAIMER</span> The information presented herein has been provided
                    by third parties and is made available solely for general information purposes. AwesomeWEB4
                    does not warrant the accuracy of this information. The information should not be construed
                    as professional or financial advice of any kind.
                </div>

                <div class="footer-container near-menu column col-12 mb-2">
                    <a target="_blank" rel="noopener noreferrer" class="btn btn-link ml-1 mr-1" href="/submit">Submit
                        a project ↗</a>
                    <a class="btn btn-link ml-1 mr-1" href="https://web4.near.page/"
                       title="About Web4" target="_blank" rel="noopener noreferrer">About Web4 ↗</a>
                    <a class="btn btn-link ml-1 mr-1" href="https://twitter.com/web4near"
                       title="Follow Web4 on Twitter" target="_blank" rel="noopener noreferrer">Twitter ↗</a>
                    <a class="btn btn-link ml-1 mr-1" href="https://github.com/zavodil/awesomeweb4"
                       title="AwesomeWeb4 Github" target="_blank" rel="noopener noreferrer">AwesomeWeb4 Github ↗</a>

                </div>

                <div class="footer-container column col-md-12">Powered by <a href="https://near.org"
                                                                             target="_blank"><strong>NEAR</strong></a>
                </div>
            </div>
        </div>
    </footer>
</div>